version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: roastlab-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roastlab_db
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - roastlab-network

  backend:
    build: ./server
    container_name: roastlab-backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - roastlab-network

  frontend:
    build: ./client
    container_name: roastlab-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - roastlab-network

networks:
  roastlab-network:
    driver: bridge
